from .exgauster import *
from .request_message import RequestMessage


def build_exgauster_1_u_171(msg: RequestMessage) -> Exgauster:
    exgauster: Exgauster = Exgauster(
        bearing_1=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_27_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_65_,
                    alarm_min=msg.SM_Exgauster__2_74_,
                    warning_max=msg.SM_Exgauster__2_83_,
                    warning_min=msg.SM_Exgauster__2_92_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_2_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_139_,
                        alarm_min=msg.SM_Exgauster__2_151_,
                        warning_max=msg.SM_Exgauster__2_163_,
                        warning_min=msg.SM_Exgauster__2_175_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_0_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_137_,
                        alarm_min=msg.SM_Exgauster__2_149_,
                        warning_max=msg.SM_Exgauster__2_161_,
                        warning_min=msg.SM_Exgauster__2_173_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_1_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_138_,
                        alarm_min=msg.SM_Exgauster__2_150_,
                        warning_max=msg.SM_Exgauster__2_162_,
                        warning_min=msg.SM_Exgauster__2_174_
                    )
                )
            )
        ),
        bearing_2=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_28_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_66_,
                    alarm_min=msg.SM_Exgauster__2_75_,
                    warning_max=msg.SM_Exgauster__2_84_,
                    warning_min=msg.SM_Exgauster__2_93_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_5_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_142_,
                        alarm_min=msg.SM_Exgauster__2_154_,
                        warning_max=msg.SM_Exgauster__2_166_,
                        warning_min=msg.SM_Exgauster__2_178_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_3_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_140_,
                        alarm_min=msg.SM_Exgauster__2_152_,
                        warning_max=msg.SM_Exgauster__2_164_,
                        warning_min=msg.SM_Exgauster__2_176_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_4_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_141_,
                        alarm_min=msg.SM_Exgauster__2_153_,
                        warning_max=msg.SM_Exgauster__2_165_,
                        warning_min=msg.SM_Exgauster__2_177_
                    )
                )
            )
        ),
        bearing_3=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_29_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_67_,
                    alarm_min=msg.SM_Exgauster__2_76_,
                    warning_max=msg.SM_Exgauster__2_85_,
                    warning_min=msg.SM_Exgauster__2_94_
                )
            )
        ),
        bearing_4=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_30_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_68_,
                    alarm_min=msg.SM_Exgauster__2_77_,
                    warning_max=msg.SM_Exgauster__2_86_,
                    warning_min=msg.SM_Exgauster__2_95_
                )
            )
        ),
        bearing_5=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_31_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_69_,
                    alarm_min=msg.SM_Exgauster__2_78_,
                    warning_max=msg.SM_Exgauster__2_87_,
                    warning_min=msg.SM_Exgauster__2_96_
                )
            )
        ),
        bearing_6=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_32_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_70_,
                    alarm_min=msg.SM_Exgauster__2_79_,
                    warning_max=msg.SM_Exgauster__2_88_,
                    warning_min=msg.SM_Exgauster__2_97_
                )
            )
        ),
        bearing_7=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_33_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_71_,
                    alarm_min=msg.SM_Exgauster__2_80_,
                    warning_max=msg.SM_Exgauster__2_89_,
                    warning_min=msg.SM_Exgauster__2_98_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_8_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_145_,
                        alarm_min=msg.SM_Exgauster__2_157_,
                        warning_max=msg.SM_Exgauster__2_169_,
                        warning_min=msg.SM_Exgauster__2_181_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_6_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_143_,
                        alarm_min=msg.SM_Exgauster__2_155_,
                        warning_max=msg.SM_Exgauster__2_167_,
                        warning_min=msg.SM_Exgauster__2_179_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_7_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_144_,
                        alarm_min=msg.SM_Exgauster__2_156_,
                        warning_max=msg.SM_Exgauster__2_168_,
                        warning_min=msg.SM_Exgauster__2_180_
                    )
                )
            )
        ),
        bearing_8=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_34_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_72_,
                    alarm_min=msg.SM_Exgauster__2_81_,
                    warning_max=msg.SM_Exgauster__2_90_,
                    warning_min=msg.SM_Exgauster__2_99_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_11_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_148_,
                        alarm_min=msg.SM_Exgauster__2_160_,
                        warning_max=msg.SM_Exgauster__2_172_,
                        warning_min=msg.SM_Exgauster__2_184_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_9_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_146_,
                        alarm_min=msg.SM_Exgauster__2_158_,
                        warning_max=msg.SM_Exgauster__2_170_,
                        warning_min=msg.SM_Exgauster__2_182_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_10_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_147_,
                        alarm_min=msg.SM_Exgauster__2_159_,
                        warning_max=msg.SM_Exgauster__2_171_,
                        warning_min=msg.SM_Exgauster__2_183_
                    )
                )
            )
        ),
        bearing_9=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_35_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__2_73_,
                    alarm_min=msg.SM_Exgauster__2_82_,
                    warning_max=msg.SM_Exgauster__2_91_,
                    warning_min=msg.SM_Exgauster__2_100_
                )
            )
        ),
        cooler=Cooler(
            oil=Oil(
                temperature_after=msg.SM_Exgauster__2_42_,
                temperature_before=msg.SM_Exgauster__2_41_
            ),
            water=Water(
                temperature_after=msg.SM_Exgauster__2_37_,
                temperature_before=msg.SM_Exgauster__2_36_
            )
        ),
        gas_manifold=GasManifold(
            temperature_before=msg.SM_Exgauster__2_24_,
            underpressure_before=msg.SM_Exgauster__2_61_
        ),
        valve_position=ValvePosition(
            gas_valve_closed=msg.SM_Exgauster__41_,
            gas_valve_open=msg.SM_Exgauster__42_,
            gas_valve_position=msg.SM_Exgauster__4_6_
        ),
        main_drive=MainDrive(
            rotor_current=msg.SM_Exgauster__4_2_,
            rotor_voltage=msg.SM_Exgauster__4_4_,
            stator_current=msg.SM_Exgauster__4_3_,
            stator_voltage=msg.SM_Exgauster__4_5_
        ),
        oil_system=OilSystem(
            oil_level=msg.SM_Exgauster__4_0_,
            oil_pressure=msg.SM_Exgauster__4_1_
        ),
        exgauster_work=msg.SM_Exgauster__20_
    )
    return exgauster
