from .exgauster import *
from .request_message import RequestMessage


def build_exgauster_5_x_171(msg: RequestMessage) -> Exgauster:
    exgauster: Exgauster = Exgauster(
        bearing_1=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_27_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_63_,
                    alarm_min=msg.SM_Exgauster__3_72_,
                    warning_max=msg.SM_Exgauster__3_81_,
                    warning_min=msg.SM_Exgauster__3_90_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_2_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_137_,
                        alarm_min=msg.SM_Exgauster__3_149_,
                        warning_max=msg.SM_Exgauster__3_161_,
                        warning_min=msg.SM_Exgauster__3_173_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_0_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_135_,
                        alarm_min=msg.SM_Exgauster__3_147_,
                        warning_max=msg.SM_Exgauster__3_159_,
                        warning_min=msg.SM_Exgauster__3_171_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_1_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_136_,
                        alarm_min=msg.SM_Exgauster__3_148_,
                        warning_max=msg.SM_Exgauster__3_160_,
                        warning_min=msg.SM_Exgauster__3_172_
                    )
                )
            )
        ),
        bearing_2=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_28_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_64_,
                    alarm_min=msg.SM_Exgauster__3_73_,
                    warning_max=msg.SM_Exgauster__3_82_,
                    warning_min=msg.SM_Exgauster__3_91_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_5_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_140_,
                        alarm_min=msg.SM_Exgauster__3_152_,
                        warning_max=msg.SM_Exgauster__3_164_,
                        warning_min=msg.SM_Exgauster__3_176_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_3_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_138_,
                        alarm_min=msg.SM_Exgauster__3_150_,
                        warning_max=msg.SM_Exgauster__3_162_,
                        warning_min=msg.SM_Exgauster__3_174_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_4_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_139_,
                        alarm_min=msg.SM_Exgauster__3_151_,
                        warning_max=msg.SM_Exgauster__3_163_,
                        warning_min=msg.SM_Exgauster__3_175_
                    )
                )
            )
        ),
        bearing_3=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_29_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_65_,
                    alarm_min=msg.SM_Exgauster__3_74_,
                    warning_max=msg.SM_Exgauster__3_83_,
                    warning_min=msg.SM_Exgauster__3_92_
                )
            )
        ),
        bearing_4=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_30_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_66_,
                    alarm_min=msg.SM_Exgauster__3_75_,
                    warning_max=msg.SM_Exgauster__3_84_,
                    warning_min=msg.SM_Exgauster__3_93_
                )
            )
        ),
        bearing_5=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_31_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_67_,
                    alarm_min=msg.SM_Exgauster__3_76_,
                    warning_max=msg.SM_Exgauster__3_85_,
                    warning_min=msg.SM_Exgauster__3_94_
                )
            )
        ),
        bearing_6=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_32_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_68_,
                    alarm_min=msg.SM_Exgauster__3_77_,
                    warning_max=msg.SM_Exgauster__3_86_,
                    warning_min=msg.SM_Exgauster__3_95_
                )
            )
        ),
        bearing_7=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_33_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_69_,
                    alarm_min=msg.SM_Exgauster__3_78_,
                    warning_max=msg.SM_Exgauster__3_87_,
                    warning_min=msg.SM_Exgauster__3_96_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_8_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_143_,
                        alarm_min=msg.SM_Exgauster__3_155_,
                        warning_max=msg.SM_Exgauster__3_167_,
                        warning_min=msg.SM_Exgauster__3_179_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_6_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_141_,
                        alarm_min=msg.SM_Exgauster__3_153_,
                        warning_max=msg.SM_Exgauster__3_165_,
                        warning_min=msg.SM_Exgauster__3_177_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_7_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_142_,
                        alarm_min=msg.SM_Exgauster__3_154_,
                        warning_max=msg.SM_Exgauster__3_166_,
                        warning_min=msg.SM_Exgauster__3_178_
                    )
                )
            )
        ),
        bearing_8=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_34_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_70_,
                    alarm_min=msg.SM_Exgauster__3_79_,
                    warning_max=msg.SM_Exgauster__3_88_,
                    warning_min=msg.SM_Exgauster__3_97_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_11_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_146_,
                        alarm_min=msg.SM_Exgauster__3_158_,
                        warning_max=msg.SM_Exgauster__3_170_,
                        warning_min=msg.SM_Exgauster__3_182_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_9_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_144_,
                        alarm_min=msg.SM_Exgauster__3_156_,
                        warning_max=msg.SM_Exgauster__3_168_,
                        warning_min=msg.SM_Exgauster__3_180_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_10_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_145_,
                        alarm_min=msg.SM_Exgauster__3_157_,
                        warning_max=msg.SM_Exgauster__3_169_,
                        warning_min=msg.SM_Exgauster__3_181_
                    )
                )
            )
        ),
        bearing_9=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_35_,
                settings=SettingsInt(
                    alarm_max=msg.SM_Exgauster__3_71_,
                    alarm_min=msg.SM_Exgauster__3_80_,
                    warning_max=msg.SM_Exgauster__3_89_,
                    warning_min=msg.SM_Exgauster__3_98_
                )
            )
        ),
        cooler=Cooler(
            oil=Oil(
                temperature_after=msg.SM_Exgauster__3_42_,
                temperature_before=msg.SM_Exgauster__3_41_
            ),
            water=Water(
                temperature_after=msg.SM_Exgauster__3_37_,
                temperature_before=msg.SM_Exgauster__3_36_
            )
        ),
        gas_manifold=GasManifold(
            temperature_before=msg.SM_Exgauster__3_24_,
            underpressure_before=msg.SM_Exgauster__3_61_
        ),
        valve_position=ValvePosition(
            gas_valve_closed=msg.SM_Exgauster__51_,
            gas_valve_open=msg.SM_Exgauster__52_,
            gas_valve_position=msg.SM_Exgauster__5_6_
        ),
        main_drive=MainDrive(
            rotor_current=msg.SM_Exgauster__5_2_,
            rotor_voltage=msg.SM_Exgauster__5_4_,
            stator_current=msg.SM_Exgauster__5_3_,
            stator_voltage=msg.SM_Exgauster__5_5_
        ),
        oil_system=OilSystem(
            oil_level=msg.SM_Exgauster__5_0_,
            oil_pressure=msg.SM_Exgauster__5_1_
        ),
        exgauster_work=msg.SM_Exgauster__30_
    )
    return exgauster
