version: '3'

services:
  # mongo db service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    volumes:
      - ./data:/data/db

  # application service
  backend:
    build: .
    command: python /backend/run.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - mongo
    restart: always

  frontend:
    container_name: frontend
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
