from .exgauster import *
from .request_message import RequestMessage


def build_exgauster_2_u_172(msg: RequestMessage) -> Exgauster:
    """
    Билд для Эксгаустера № 2 (У-172)
    """
    exgauster: Exgauster = Exgauster(
        bearing_1=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_43_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_101_,
                    alarm_min=msg.SM_Exgauster__2_110_,
                    warning_max=msg.SM_Exgauster__2_119_,
                    warning_min=msg.SM_Exgauster__2_128_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_14_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_187_,
                        alarm_min=msg.SM_Exgauster__2_199_,
                        warning_max=msg.SM_Exgauster__2_211_,
                        warning_min=msg.SM_Exgauster__2_223_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_12_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_185_,
                        alarm_min=msg.SM_Exgauster__2_197_,
                        warning_max=msg.SM_Exgauster__2_209_,
                        warning_min=msg.SM_Exgauster__2_221_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_13_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_186_,
                        alarm_min=msg.SM_Exgauster__2_198_,
                        warning_max=msg.SM_Exgauster__2_210_,
                        warning_min=msg.SM_Exgauster__2_222_
                    )
                )
            )
        ),
        bearing_2=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_44_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_102_,
                    alarm_min=msg.SM_Exgauster__2_111_,
                    warning_max=msg.SM_Exgauster__2_120_,
                    warning_min=msg.SM_Exgauster__2_129_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_17_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_190_,
                        alarm_min=msg.SM_Exgauster__2_202_,
                        warning_max=msg.SM_Exgauster__2_214_,
                        warning_min=msg.SM_Exgauster__2_226_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_15_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_188_,
                        alarm_min=msg.SM_Exgauster__2_200_,
                        warning_max=msg.SM_Exgauster__2_212_,
                        warning_min=msg.SM_Exgauster__2_224_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_16_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_189_,
                        alarm_min=msg.SM_Exgauster__2_201_,
                        warning_max=msg.SM_Exgauster__2_213_,
                        warning_min=msg.SM_Exgauster__2_225_
                    )
                )
            )
        ),
        bearing_3=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_45_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_103_,
                    alarm_min=msg.SM_Exgauster__2_112_,
                    warning_max=msg.SM_Exgauster__2_121_,
                    warning_min=msg.SM_Exgauster__2_130_
                )
            )
        ),
        bearing_4=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_47_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_104_,
                    alarm_min=msg.SM_Exgauster__2_113_,
                    warning_max=msg.SM_Exgauster__2_122_,
                    warning_min=msg.SM_Exgauster__2_131_
                )
            )
        ),
        bearing_5=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_48_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_105_,
                    alarm_min=msg.SM_Exgauster__2_114_,
                    warning_max=msg.SM_Exgauster__2_123_,
                    warning_min=msg.SM_Exgauster__2_132_
                )
            )
        ),
        bearing_6=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_49_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_106_,
                    alarm_min=msg.SM_Exgauster__2_115_,
                    warning_max=msg.SM_Exgauster__2_124_,
                    warning_min=msg.SM_Exgauster__2_133_
                )
            )
        ),
        bearing_7=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_50_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_107_,
                    alarm_min=msg.SM_Exgauster__2_116_,
                    warning_max=msg.SM_Exgauster__2_125_,
                    warning_min=msg.SM_Exgauster__2_134_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_20_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_193_,
                        alarm_min=msg.SM_Exgauster__2_205_,
                        warning_max=msg.SM_Exgauster__2_217_,
                        warning_min=msg.SM_Exgauster__2_229_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_18_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_191_,
                        alarm_min=msg.SM_Exgauster__2_203_,
                        warning_max=msg.SM_Exgauster__2_215_,
                        warning_min=msg.SM_Exgauster__2_227_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_19_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_192_,
                        alarm_min=msg.SM_Exgauster__2_204_,
                        warning_max=msg.SM_Exgauster__2_216_,
                        warning_min=msg.SM_Exgauster__2_228_
                    )
                )
            )
        ),
        bearing_8=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_51_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_108_,
                    alarm_min=msg.SM_Exgauster__2_117_,
                    warning_max=msg.SM_Exgauster__2_126_,
                    warning_min=msg.SM_Exgauster__2_135_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__2_23_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_196_,
                        alarm_min=msg.SM_Exgauster__2_208_,
                        warning_max=msg.SM_Exgauster__2_220_,
                        warning_min=msg.SM_Exgauster__2_232_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__2_21_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_194_,
                        alarm_min=msg.SM_Exgauster__2_206_,
                        warning_max=msg.SM_Exgauster__2_218_,
                        warning_min=msg.SM_Exgauster__2_230_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__2_22_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__2_195_,
                        alarm_min=msg.SM_Exgauster__2_207_,
                        warning_max=msg.SM_Exgauster__2_219_,
                        warning_min=msg.SM_Exgauster__2_231_
                    )
                )
            )
        ),
        bearing_9=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__2_52_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__2_109_,
                    alarm_min=msg.SM_Exgauster__2_118_,
                    warning_max=msg.SM_Exgauster__2_127_,
                    warning_min=msg.SM_Exgauster__2_136_
                )
            )
        ),
        cooler=Cooler(
            oil=Oil(
                temperature_after=msg.SM_Exgauster__2_60_,
                temperature_before=msg.SM_Exgauster__2_59_
            ),
            water=Water(
                temperature_after=msg.SM_Exgauster__2_54_,
                temperature_before=msg.SM_Exgauster__2_53_
            )
        ),
        gas_manifold=GasManifold(
            temperature_before=msg.SM_Exgauster__2_25_,
            underpressure_before=msg.SM_Exgauster__2_62_
        ),
        valve_position=ValvePosition(
            gas_valve_closed=msg.SM_Exgauster__46_,
            gas_valve_open=msg.SM_Exgauster__47_,
            gas_valve_position=msg.SM_Exgauster__4_13_
        ),
        main_drive=MainDrive(
            rotor_current=msg.SM_Exgauster__4_9_,
            rotor_voltage=msg.SM_Exgauster__4_11_,
            stator_current=msg.SM_Exgauster__4_10_,
            stator_voltage=msg.SM_Exgauster__4_12_
        ),
        oil_system=OilSystem(
            oil_level=msg.SM_Exgauster__4_7_,
            oil_pressure=msg.SM_Exgauster__4_8_
        ),
        exgauster_work=msg.SM_Exgauster__21_
    )
    return exgauster
