from .exgauster import *
from .request_message import RequestMessage


def build_exgauster_4_f_172(msg: RequestMessage) -> Exgauster:
    """
    Билд для Эксгаустера № 4 (Ф-172)
    """
    exgauster: Exgauster = Exgauster(
        bearing_1=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_43_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_99_,
                    alarm_min=msg.SM_Exgauster__0_108_,
                    warning_max=msg.SM_Exgauster__0_117_,
                    warning_min=msg.SM_Exgauster__0_126_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__0_14_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_185_,
                        alarm_min=msg.SM_Exgauster__0_197_,
                        warning_max=msg.SM_Exgauster__0_209_,
                        warning_min=msg.SM_Exgauster__0_221_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__0_12_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_183_,
                        alarm_min=msg.SM_Exgauster__0_195_,
                        warning_max=msg.SM_Exgauster__0_207_,
                        warning_min=msg.SM_Exgauster__0_219_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__0_13_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_184_,
                        alarm_min=msg.SM_Exgauster__0_196_,
                        warning_max=msg.SM_Exgauster__0_208_,
                        warning_min=msg.SM_Exgauster__0_220_
                    )
                )
            )
        ),
        bearing_2=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_44_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_100_,
                    alarm_min=msg.SM_Exgauster__0_109_,
                    warning_max=msg.SM_Exgauster__0_118_,
                    warning_min=msg.SM_Exgauster__0_127_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__0_17_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_188_,
                        alarm_min=msg.SM_Exgauster__0_200_,
                        warning_max=msg.SM_Exgauster__0_212_,
                        warning_min=msg.SM_Exgauster__0_224_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__0_15_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_186_,
                        alarm_min=msg.SM_Exgauster__0_198_,
                        warning_max=msg.SM_Exgauster__0_210_,
                        warning_min=msg.SM_Exgauster__0_222_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__0_16_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_187_,
                        alarm_min=msg.SM_Exgauster__0_199_,
                        warning_max=msg.SM_Exgauster__0_211_,
                        warning_min=msg.SM_Exgauster__0_223_
                    )
                )
            )
        ),
        bearing_3=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_45_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_101_,
                    alarm_min=msg.SM_Exgauster__0_110_,
                    warning_max=msg.SM_Exgauster__0_119_,
                    warning_min=msg.SM_Exgauster__0_128_
                )
            )
        ),
        bearing_4=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_47_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_102_,
                    alarm_min=msg.SM_Exgauster__0_111_,
                    warning_max=msg.SM_Exgauster__0_120_,
                    warning_min=msg.SM_Exgauster__0_129_
                )
            )
        ),
        bearing_5=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_48_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_103_,
                    alarm_min=msg.SM_Exgauster__0_112_,
                    warning_max=msg.SM_Exgauster__0_121_,
                    warning_min=msg.SM_Exgauster__0_130_
                )
            )
        ),
        bearing_6=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_49_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_104_,
                    alarm_min=msg.SM_Exgauster__0_113_,
                    warning_max=msg.SM_Exgauster__0_122_,
                    warning_min=msg.SM_Exgauster__0_131_
                )
            )
        ),
        bearing_7=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_50_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_105_,
                    alarm_min=msg.SM_Exgauster__0_114_,
                    warning_max=msg.SM_Exgauster__0_123_,
                    warning_min=msg.SM_Exgauster__0_132_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__0_20_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_191_,
                        alarm_min=msg.SM_Exgauster__0_203_,
                        warning_max=msg.SM_Exgauster__0_215_,
                        warning_min=msg.SM_Exgauster__0_227_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__0_18_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_189_,
                        alarm_min=msg.SM_Exgauster__0_201_,
                        warning_max=msg.SM_Exgauster__0_213_,
                        warning_min=msg.SM_Exgauster__0_225_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__0_19_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_190_,
                        alarm_min=msg.SM_Exgauster__0_202_,
                        warning_max=msg.SM_Exgauster__0_214_,
                        warning_min=msg.SM_Exgauster__0_226_
                    )
                )
            )
        ),
        bearing_8=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_51_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_106_,
                    alarm_min=msg.SM_Exgauster__0_115_,
                    warning_max=msg.SM_Exgauster__0_124_,
                    warning_min=msg.SM_Exgauster__0_133_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__0_23_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_194_,
                        alarm_min=msg.SM_Exgauster__0_206_,
                        warning_max=msg.SM_Exgauster__0_218_,
                        warning_min=msg.SM_Exgauster__0_230_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__0_21_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_192_,
                        alarm_min=msg.SM_Exgauster__0_204_,
                        warning_max=msg.SM_Exgauster__0_216_,
                        warning_min=msg.SM_Exgauster__0_228_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__0_22_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__0_193_,
                        alarm_min=msg.SM_Exgauster__0_205_,
                        warning_max=msg.SM_Exgauster__0_217_,
                        warning_min=msg.SM_Exgauster__0_229_
                    )
                )
            )
        ),
        bearing_9=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__0_52_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__0_107_,
                    alarm_min=msg.SM_Exgauster__0_116_,
                    warning_max=msg.SM_Exgauster__0_125_,
                    warning_min=msg.SM_Exgauster__0_134_
                )
            )
        ),
        cooler=Cooler(
            oil=Oil(
                temperature_after=msg.SM_Exgauster__0_60_,
                temperature_before=msg.SM_Exgauster__0_59_
            ),
            water=Water(
                temperature_after=msg.SM_Exgauster__0_54_,
                temperature_before=msg.SM_Exgauster__0_53_
            )
        ),
        gas_manifold=GasManifold(
            temperature_before=msg.SM_Exgauster__0_25_,
            underpressure_before=msg.SM_Exgauster__0_62_
        ),
        valve_position=ValvePosition(
            gas_valve_closed=msg.SM_Exgauster__16_,
            gas_valve_open=msg.SM_Exgauster__17_,
            gas_valve_position=msg.SM_Exgauster__1_13_
        ),
        main_drive=MainDrive(
            rotor_current=msg.SM_Exgauster__1_9_,
            rotor_voltage=msg.SM_Exgauster__1_11_,
            stator_current=msg.SM_Exgauster__1_10_,
            stator_voltage=msg.SM_Exgauster__1_12_
        ),
        oil_system=OilSystem(
            oil_level=msg.SM_Exgauster__1_7_,
            oil_pressure=msg.SM_Exgauster__1_8_
        ),
        exgauster_work=msg.SM_Exgauster__01_
    )
    return exgauster
