from .exgauster import *
from .request_message import RequestMessage


def build_exgauster_6_x_172(msg: RequestMessage) -> Exgauster:
    """
    Билд для Эксгаустера № 6 (X-172)
    """
    exgauster: Exgauster = Exgauster(
        bearing_1=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_43_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_99_,
                    alarm_min=msg.SM_Exgauster__3_108_,
                    warning_max=msg.SM_Exgauster__3_117_,
                    warning_min=msg.SM_Exgauster__3_126_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_14_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_185_,
                        alarm_min=msg.SM_Exgauster__3_197_,
                        warning_max=msg.SM_Exgauster__3_209_,
                        warning_min=msg.SM_Exgauster__3_221_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_12_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_183_,
                        alarm_min=msg.SM_Exgauster__3_195_,
                        warning_max=msg.SM_Exgauster__3_207_,
                        warning_min=msg.SM_Exgauster__3_219_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_13_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_184_,
                        alarm_min=msg.SM_Exgauster__3_196_,
                        warning_max=msg.SM_Exgauster__3_208_,
                        warning_min=msg.SM_Exgauster__3_220_
                    )
                )
            )
        ),
        bearing_2=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_44_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_100_,
                    alarm_min=msg.SM_Exgauster__3_109_,
                    warning_max=msg.SM_Exgauster__3_118_,
                    warning_min=msg.SM_Exgauster__3_127_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_17_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_188_,
                        alarm_min=msg.SM_Exgauster__3_200_,
                        warning_max=msg.SM_Exgauster__3_212_,
                        warning_min=msg.SM_Exgauster__3_224_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_15_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_186_,
                        alarm_min=msg.SM_Exgauster__3_198_,
                        warning_max=msg.SM_Exgauster__3_210_,
                        warning_min=msg.SM_Exgauster__3_222_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_16_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_187_,
                        alarm_min=msg.SM_Exgauster__3_199_,
                        warning_max=msg.SM_Exgauster__3_211_,
                        warning_min=msg.SM_Exgauster__3_223_
                    )
                )
            )
        ),
        bearing_3=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_45_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_101_,
                    alarm_min=msg.SM_Exgauster__3_110_,
                    warning_max=msg.SM_Exgauster__3_119_,
                    warning_min=msg.SM_Exgauster__3_128_
                )
            )
        ),
        bearing_4=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_47_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_102_,
                    alarm_min=msg.SM_Exgauster__3_111_,
                    warning_max=msg.SM_Exgauster__3_120_,
                    warning_min=msg.SM_Exgauster__3_129_
                )
            )
        ),
        bearing_5=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_48_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_103_,
                    alarm_min=msg.SM_Exgauster__3_112_,
                    warning_max=msg.SM_Exgauster__3_121_,
                    warning_min=msg.SM_Exgauster__3_130_
                )
            )
        ),
        bearing_6=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_49_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_104_,
                    alarm_min=msg.SM_Exgauster__3_113_,
                    warning_max=msg.SM_Exgauster__3_122_,
                    warning_min=msg.SM_Exgauster__3_131_
                )
            )
        ),
        bearing_7=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_50_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_105_,
                    alarm_min=msg.SM_Exgauster__3_114_,
                    warning_max=msg.SM_Exgauster__3_123_,
                    warning_min=msg.SM_Exgauster__3_132_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_20_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_191_,
                        alarm_min=msg.SM_Exgauster__3_203_,
                        warning_max=msg.SM_Exgauster__3_215_,
                        warning_min=msg.SM_Exgauster__3_227_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_18_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_189_,
                        alarm_min=msg.SM_Exgauster__3_201_,
                        warning_max=msg.SM_Exgauster__3_213_,
                        warning_min=msg.SM_Exgauster__3_225_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_19_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_190_,
                        alarm_min=msg.SM_Exgauster__3_202_,
                        warning_max=msg.SM_Exgauster__3_214_,
                        warning_min=msg.SM_Exgauster__3_226_
                    )
                )
            )
        ),
        bearing_8=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_51_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_106_,
                    alarm_min=msg.SM_Exgauster__3_115_,
                    warning_max=msg.SM_Exgauster__3_124_,
                    warning_min=msg.SM_Exgauster__3_133_
                )
            ),
            vibration=Vibration(
                axial=AxialVibration(
                    value=msg.SM_Exgauster__3_23_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_194_,
                        alarm_min=msg.SM_Exgauster__3_206_,
                        warning_max=msg.SM_Exgauster__3_218_,
                        warning_min=msg.SM_Exgauster__3_230_
                    )
                ),
                horizontal=HorizontalVibration(
                    value=msg.SM_Exgauster__3_21_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_192_,
                        alarm_min=msg.SM_Exgauster__3_204_,
                        warning_max=msg.SM_Exgauster__3_216_,
                        warning_min=msg.SM_Exgauster__3_228_
                    )
                ),
                vertical=VerticalVibration(
                    value=msg.SM_Exgauster__3_22_,
                    settings=SettingsFloat(
                        alarm_max=msg.SM_Exgauster__3_193_,
                        alarm_min=msg.SM_Exgauster__3_205_,
                        warning_max=msg.SM_Exgauster__3_217_,
                        warning_min=msg.SM_Exgauster__3_229_
                    )
                )
            )
        ),
        bearing_9=Bearing(
            heating_temperature=HeatingTemperature(
                temperature=msg.SM_Exgauster__3_52_,
                settings=SettingsFloat(
                    alarm_max=msg.SM_Exgauster__3_107_,
                    alarm_min=msg.SM_Exgauster__3_116_,
                    warning_max=msg.SM_Exgauster__3_125_,
                    warning_min=msg.SM_Exgauster__3_134_
                )
            )
        ),
        cooler=Cooler(
            oil=Oil(
                temperature_after=msg.SM_Exgauster__3_60_,
                temperature_before=msg.SM_Exgauster__3_59_
            ),
            water=Water(
                temperature_after=msg.SM_Exgauster__3_54_,
                temperature_before=msg.SM_Exgauster__3_53_
            )
        ),
        gas_manifold=GasManifold(
            temperature_before=msg.SM_Exgauster__3_25_,
            underpressure_before=msg.SM_Exgauster__3_62_
        ),
        valve_position=ValvePosition(
            gas_valve_closed=msg.SM_Exgauster__56_,
            gas_valve_open=msg.SM_Exgauster__57_,
            gas_valve_position=msg.SM_Exgauster__5_13_
        ),
        main_drive=MainDrive(
            rotor_current=msg.SM_Exgauster__5_9_,
            rotor_voltage=msg.SM_Exgauster__5_11_,
            stator_current=msg.SM_Exgauster__5_10_,
            stator_voltage=msg.SM_Exgauster__5_12_
        ),
        oil_system=OilSystem(
            oil_level=msg.SM_Exgauster__5_7_,
            oil_pressure=msg.SM_Exgauster__5_8_
        ),
        exgauster_work=msg.SM_Exgauster__31_
    )
    return exgauster
